# Generated by Django 3.2.6 on 2021-08-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_auto_20210825_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
